#	Problem 2: Even Fibonacci numbers
#   Each new term in the Fibonacci sequence is generated by
#   adding the previous two terms. By starting with 1 and 2,
#   the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#   By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#   find the sum of the even-valued terms.

def FibonacciNumbers():
	sumNumb = 2
	preFibNumb = 1
	fibNumb = 2
	while(1==1):
		next = fibNumb+preFibNumb
		preFibNumb = next + fibNumb
		fibNumb = next+preFibNumb
		if fibNumb>4000000:
			break
		sumNumb += fibNumb
	return sumNumb

print FibonacciNumbers();